import assert from "node:assert/strict";
import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { inspectInstallation } from "../src/doctor.mjs";
import { installBridgecode } from "../src/install.mjs";
import { parseBootstrap } from "../src/instructions.mjs";
import { CORE_PATH, HOOK_PATH, PAYLOAD_DIR } from "../src/manifest.mjs";
import { updateBridgecode } from "../src/update.mjs";
import { fixture, PACKAGE_ROOT, simulatedPackage, snapshot, MANAGED_PATHS, codexInstall, codexSnapshot } from "./helpers.mjs";
const options=root=>({project:root,packageRoot:PACKAGE_ROOT});
const exists=p=>access(p).then(()=>true,()=>false);
test("install, doctor, true no-op update and projected dry-run",async t=>{
 const root=await fixture(t);const before=await snapshot(root);
 const dry=await installBridgecode({...options(root),dryRun:true});
 assert.ok(dry.changes.length);assert.deepEqual(await snapshot(root),before);
 const out=await installBridgecode(options(root));
 assert.equal(out.verified,true);assert.equal(out.edition,"claude-code");assert.equal(out.coreAutoloaded,true);assert.equal(out.codexDetected,false);
 for(const p of [...MANAGED_PATHS,HOOK_PATH])assert.deepEqual(await readFile(path.join(root,p)),await readFile(path.join(PACKAGE_ROOT,p===HOOK_PATH?"hooks/bridgecode-turn.mjs":path.join(PAYLOAD_DIR,p))),p);
 assert.equal(await exists(path.join(root,"AGENTS.md")),false,"never creates AGENTS.md");
 const installed=await snapshot(root);
 assert.equal((await updateBridgecode(options(root))).changes.length,0);
 assert.deepEqual(await snapshot(root),installed);
 assert.equal((await inspectInstallation(options(root))).ok,true);
});
test("CLAUDE.md user content is preserved and the bootstrap imports the core",async t=>{
 const root=await fixture(t);const text="# Existing\r\n\r\nKeep π and spacing.  \r\n";
 await writeFile(path.join(root,"CLAUDE.md"),text);
 await installBridgecode(options(root));
 const claude=await readFile(path.join(root,"CLAUDE.md"),"utf8");
 assert.ok(claude.startsWith(text));
 const block=parseBootstrap(claude).block;
 assert.ok(block.includes("\r\n@.claude/bridgecode/CORE.md\r\n"),"CRLF preserved and root import path");
 await updateBridgecode(options(root));
 assert.ok((await readFile(path.join(root,"CLAUDE.md"),"utf8")).startsWith(text));
});
test("custom .claude/CLAUDE.md imports the core relative to its own directory",async t=>{
 const root=await fixture(t);
 await installBridgecode({...options(root),instructionFile:[".claude/CLAUDE.md"]});
 const custom=parseBootstrap(await readFile(path.join(root,".claude/CLAUDE.md"),"utf8")).block;
 assert.ok(custom.split("\n").includes("@bridgecode/CORE.md"));
 assert.ok(parseBootstrap(await readFile(path.join(root,"CLAUDE.md"),"utf8")).block.includes("@"+CORE_PATH));
 assert.equal((await inspectInstallation(options(root))).ok,true);
 assert.equal((await updateBridgecode(options(root))).changes.length,0);
});
test("coexists with a Codex edition: Codex files stay byte-identical",async t=>{
 const root=await fixture(t);await codexInstall(root);
 const codexBootstrap='<!-- bridgecode:bootstrap:start version="4.3.2" schema="2" -->\nRead the complete root AGENTS.md.\n<!-- bridgecode:bootstrap:end -->';
 const userClaude="# Team notes\n"+codexBootstrap+"\n";
 await writeFile(path.join(root,"CLAUDE.md"),userClaude);
 await writeFile(path.join(root,".bridgecode/installation.json"),JSON.stringify({package:"@bridgecode/cli",version:"4.3.2",schemaVersion:2,instructionFiles:["CLAUDE.md","GEMINI.md"]})+"\n");
 const codex=await codexSnapshot(root);
 const out=await installBridgecode(options(root));
 assert.equal(out.codexDetected,true);assert.equal(out.codexBootstrapInClaude,true);
 assert.equal(out.codexRemovalCommand,'npx -y @bridgecode/cli@4.3.2 update --project . --instruction-files agents --instruction-file "GEMINI.md"',"re-lists the Codex edition's other bootstraps, drops CLAUDE.md");
 const claude=await readFile(path.join(root,"CLAUDE.md"),"utf8");
 assert.ok(claude.startsWith(userClaude),"Codex bootstrap untouched");
 assert.ok(parseBootstrap(claude));
 assert.deepEqual(await codexSnapshot(root),codex);
 await updateBridgecode(options(root));
 await updateBridgecode({...options(root),hooks:false});
 const report=await inspectInstallation(options(root));
 assert.equal(report.ok,true);
 assert.ok(report.warnings.some(w=>/Codex edition installation detected/.test(w)));
 assert.ok(report.warnings.some(w=>/Codex edition bootstrap/.test(w)&&w.includes(out.codexRemovalCommand)));
 assert.deepEqual(await codexSnapshot(root),codex);
});
test("agentic memory is never written by install or update",async t=>{
 const root=await fixture(t);await mkdir(path.join(root,"agentic"));
 const architecture="# Architecture\r\nVerified ownership → src/main.mjs\r\n## Imported repository constraints — verification pending\n- Keep\n",analysis="Another active task\n";
 await writeFile(path.join(root,"agentic/architecture.md"),architecture);await writeFile(path.join(root,"agentic/analysis.md"),analysis);
 await installBridgecode(options(root));
 await updateBridgecode({project:root,packageRoot:await simulatedPackage(t)});
 assert.equal(await readFile(path.join(root,"agentic/architecture.md"),"utf8"),architecture);
 assert.equal(await readFile(path.join(root,"agentic/analysis.md"),"utf8"),analysis);
});
test("next release updates from its trusted snapshot and verifies",async t=>{
 const root=await fixture(t);await installBridgecode(options(root));
 const pkg=await simulatedPackage(t);
 await updateBridgecode({project:root,packageRoot:pkg});
 assert.match(await readFile(path.join(root,".claude/bridgecode/writing.md"),"utf8"),/Simulation 4\.3\.3/);
 assert.match(await readFile(path.join(root,"CLAUDE.md"),"utf8"),/version="4\.3\.3"/);
 const report=await inspectInstallation({project:root,packageRoot:pkg});
 assert.equal(report.ok,true);assert.equal(report.version,"4.3.3");
 assert.equal((await updateBridgecode({project:root,packageRoot:pkg})).changes.length,0);
});
test("next-release failure restores all original bytes",async t=>{
 const root=await fixture(t);await installBridgecode(options(root));const before=await snapshot(root);
 const pkg=await simulatedPackage(t);
 await assert.rejects(updateBridgecode({project:root,packageRoot:pkg,transactionFailAfterWrites:2}),/rolled back.*Simulated interruption/s);
 assert.deepEqual(await snapshot(root),before);
});
test("settings.json keeps unrelated keys, events and entries; disabling removes only Bridgecode entries",async t=>{
 const root=await fixture(t);await mkdir(path.join(root,".claude"));
 const custom={hooks:[{type:"command",command:"echo custom"}]};
 const stop={hooks:[{type:"command",command:"echo stop"}]};
 const settings={permissions:{allow:["Bash(npm test)"]},env:{A:"1"},hooks:{UserPromptSubmit:[custom],Stop:[stop]}};
 await writeFile(path.join(root,".claude/settings.json"),JSON.stringify(settings));
 await installBridgecode(options(root));
 let c=JSON.parse(await readFile(path.join(root,".claude/settings.json")));
 assert.deepEqual(c.permissions,settings.permissions);assert.deepEqual(c.env,settings.env);assert.deepEqual(c.hooks.Stop,[stop]);
 assert.deepEqual(c.hooks.UserPromptSubmit[0],custom);assert.equal(c.hooks.UserPromptSubmit.length,2);
 assert.equal(c.hooks.SessionStart[0].matcher,"compact");
 assert.ok(c.hooks.SessionStart[0].hooks[0].command.includes("$CLAUDE_PROJECT_DIR/.claude/hooks/bridgecode-turn.mjs"));
 await updateBridgecode({...options(root),hooks:false});
 c=JSON.parse(await readFile(path.join(root,".claude/settings.json")));
 assert.deepEqual(c,{permissions:settings.permissions,env:settings.env,hooks:{UserPromptSubmit:[custom],Stop:[stop]}});
 assert.equal(await exists(path.join(root,HOOK_PATH)),false,"retired hook script removed");
 assert.equal((await inspectInstallation(options(root))).ok,true);
 await updateBridgecode({...options(root),hooks:true});
 assert.equal((await inspectInstallation(options(root))).ok,true);
});
test("--instruction-files none removes the bootstrap; empty files are removed, user content kept",async t=>{
 const root=await fixture(t),user="# Mine\n";
 await installBridgecode({...options(root),instructionFile:[".claude/CLAUDE.md"]});
 await writeFile(path.join(root,".claude/CLAUDE.md"),user+(await readFile(path.join(root,".claude/CLAUDE.md"),"utf8")));
 // The user edit sits outside the managed block, so ownership remains intact.
 assert.equal((await inspectInstallation(options(root))).ok,true);
 const out=await updateBridgecode({...options(root),instructionFiles:"none"});
 assert.equal(out.coreAutoloaded,false);
 assert.equal(await exists(path.join(root,"CLAUDE.md")),false);
 assert.equal(await readFile(path.join(root,".claude/CLAUDE.md"),"utf8"),user.trimEnd(),"block and its separating newlines removed");
 const report=await inspectInstallation(options(root));
 assert.equal(report.ok,true);assert.ok(report.warnings.some(w=>w.includes("will not load the core automatically")));
});
test("only a root-scope bootstrap counts as autoloading the core",async t=>{
 const nested=await fixture(t),dotClaude=await fixture(t);
 const out=await installBridgecode({...options(nested),instructionFiles:"none",instructionFile:["app/CLAUDE.md"]});
 assert.equal(out.coreAutoloaded,false);
 assert.ok((await readFile(path.join(nested,"app/CLAUDE.md"),"utf8")).includes("@../.claude/bridgecode/CORE.md"));
 assert.ok((await inspectInstallation(options(nested))).warnings.some(w=>w.includes("will not load the core automatically")));
 const scoped=await installBridgecode({...options(dotClaude),instructionFiles:"none",instructionFile:[".claude/CLAUDE.md"]});
 assert.equal(scoped.coreAutoloaded,true);
 assert.ok((await readFile(path.join(dotClaude,".claude/CLAUDE.md"),"utf8")).includes("@bridgecode/CORE.md"));
 assert.ok(!(await inspectInstallation(options(dotClaude))).warnings.some(w=>w.includes("will not load the core automatically")));
});
